In [1]:
import random
import numpy as np
from lxml import etree
from datetime import datetime

In [2]:
# Load the XML file
tree = etree.parse('burma14.xml')                  # Change the name between burma and Brazil and to get desired output
elem = tree.getroot()

In [3]:
cities = elem.findall('graph/vertex')
# Get the number of cities
num_cities = len(cities)

In [4]:
num_cities

14

In [5]:
# Initialize a 2-D array to store the distances between cities
distance_matrix = [[0] * num_cities for _ in range(num_cities)]

In [6]:
distance_matrix

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [7]:
# Iterate through the XML data and fill the distance matrix
for city_id, city in enumerate(cities):
    routes = city.findall('edge')
    for route in routes:
        target_city_id = int(route.text)
        cost = float(route.get("cost"))
        distance_matrix[city_id][target_city_id] = cost

In [8]:
distance_matrix

[[0,
  153.0,
  510.0,
  706.0,
  966.0,
  581.0,
  455.0,
  70.0,
  160.0,
  372.0,
  157.0,
  567.0,
  342.0,
  398.0],
 [153.0,
  0,
  422.0,
  664.0,
  997.0,
  598.0,
  507.0,
  197.0,
  311.0,
  479.0,
  310.0,
  581.0,
  417.0,
  376.0],
 [510.0,
  422.0,
  0,
  289.0,
  744.0,
  390.0,
  437.0,
  491.0,
  645.0,
  880.0,
  618.0,
  374.0,
  455.0,
  211.0],
 [706.0,
  664.0,
  289.0,
  0,
  491.0,
  265.0,
  410.0,
  664.0,
  804.0,
  1070.0,
  768.0,
  259.0,
  499.0,
  310.0],
 [966.0,
  997.0,
  744.0,
  491.0,
  0,
  400.0,
  514.0,
  902.0,
  990.0,
  1261.0,
  947.0,
  418.0,
  635.0,
  636.0],
 [581.0,
  598.0,
  390.0,
  265.0,
  400.0,
  0,
  168.0,
  522.0,
  634.0,
  910.0,
  593.0,
  19.0,
  284.0,
  239.0],
 [455.0,
  507.0,
  437.0,
  410.0,
  514.0,
  168.0,
  0,
  389.0,
  482.0,
  757.0,
  439.0,
  163.0,
  124.0,
  232.0],
 [70.0,
  197.0,
  491.0,
  664.0,
  902.0,
  522.0,
  389.0,
  0,
  154.0,
  406.0,
  133.0,
  508.0,
  273.0,
  355.0],
 [160.0,
  311.0,

In [9]:
# Print the distance matrix
for i in range(num_cities):
    for j in range(num_cities):
        print(f'Distance from city {i} to city {j} = {distance_matrix[i][j]}')


Distance from city 0 to city 0 = 0
Distance from city 0 to city 1 = 153.0
Distance from city 0 to city 2 = 510.0
Distance from city 0 to city 3 = 706.0
Distance from city 0 to city 4 = 966.0
Distance from city 0 to city 5 = 581.0
Distance from city 0 to city 6 = 455.0
Distance from city 0 to city 7 = 70.0
Distance from city 0 to city 8 = 160.0
Distance from city 0 to city 9 = 372.0
Distance from city 0 to city 10 = 157.0
Distance from city 0 to city 11 = 567.0
Distance from city 0 to city 12 = 342.0
Distance from city 0 to city 13 = 398.0
Distance from city 1 to city 0 = 153.0
Distance from city 1 to city 1 = 0
Distance from city 1 to city 2 = 422.0
Distance from city 1 to city 3 = 664.0
Distance from city 1 to city 4 = 997.0
Distance from city 1 to city 5 = 598.0
Distance from city 1 to city 6 = 507.0
Distance from city 1 to city 7 = 197.0
Distance from city 1 to city 8 = 311.0
Distance from city 1 to city 9 = 479.0
Distance from city 1 to city 10 = 310.0
Distance from city 1 to city 

In [10]:
# Parameters
n_cities = num_cities  # The number of cities from the XML data
n_population = 400
mutation_rate = 0.2

In [11]:
# First step: Create the first population set of 100, randomly ordered
def genesis(n_population, n_cities):
    population_set = []
    for i in range(n_population):
        sol_i = np.random.permutation(n_cities)  # Randomly shuffle the cities
        print(sol_i)
        population_set.append(sol_i)
    return np.array(population_set)

In [12]:
population_set = genesis(n_population, n_cities)      # Randomly ordered 100 city routes (aka population set of 100 routes)

[11  0  1 12  2  4  8 13  3  7  5  9  6 10]
[11  6  5  8  3  0 10 13 12  1  4  7  2  9]
[ 7  3  6 12  0  1  8  5  9 10  4 13  2 11]
[ 4  1  9  8  3  0 10 12 13 11  6  2  7  5]
[ 8  6 12  7  4 11  2  9  5 10 13  3  0  1]
[ 7 10  9  2  1 12 11  6  8  3  4  5  0 13]
[ 6 13 10 11  9  0  2  8 12  1  3  5  4  7]
[ 1  3  0  4 11  6  9  2 12 10  5 13  8  7]
[12 13  8  9 11  6  2 10  7  4  5  1  0  3]
[13  7  8  6  1  3 11 10  0 12  5  2  9  4]
[11  0  9  6  1  4 13 10  8 12  7  3  5  2]
[ 9  2  6  8 11  3 12 10  4  0  5  1 13  7]
[ 0 11 13  6 12  7  3  1  2  5  8  9 10  4]
[11  8  5 10  7  4 12  0 13  6  9  2  3  1]
[ 5  9  3  8  1  6  0  7 10  4 13 12 11  2]
[ 3  1  0 12  8 13  7  9 10  5 11  6  4  2]
[11  4  7  9  3 10  1  5  8  2 13  6  0 12]
[ 1 11  3 12  7  9 13  0  8  4  6 10  2  5]
[ 4  0  9  2 10  8  5  3 11  6  7  1 12 13]
[ 0  2  5 10  7  8  6  9  4 12 13  1  3 11]
[ 7 11 10  5 12  1  3  2  4  6  0  9  8 13]
[ 2 13  5  8  7  3 10  4  6  9 12  0 11  1]
[ 6  8  1 13 10 12  4  0  5  3  

In [13]:
population_set

array([[11,  0,  1, ...,  9,  6, 10],
       [11,  6,  5, ...,  7,  2,  9],
       [ 7,  3,  6, ..., 13,  2, 11],
       ...,
       [ 4, 10,  5, ..., 12,  8,  0],
       [ 0, 11,  4, ...,  9, 12,  1],
       [ 2,  0, 10, ...,  5,  9, 11]])

In [14]:
def compute_city_distance(a, b):
  return distance_matrix[a][b]

In [15]:
def fitness_eval(city_list):
    total = 0
    for i in range(n_cities - 1):
        a = city_list[i]
        b = city_list[i + 1]
        total += compute_city_distance(a, b)
    # Add distance from the last city back to the starting city
    total += compute_city_distance(city_list[-1], city_list[0])
    return total

In [16]:
def get_all_fitnes(population_set):
    fitnes_list = np.zeros(n_population)

    for i in range(n_population):
        fitnes_list[i] = fitness_eval(population_set[i])

    return fitnes_list

In [17]:
# Get the fitness score for each of the routes in the population set
# and store them in a list of 100 entries. [Each entry corresponds to
# the cost (aka fitness score) to take that route and be back to
# starting city.]
fitnes_list = get_all_fitnes(population_set)

In [18]:
# When we print this list, each entry corresponds to
# the cost of traveling in that route. This is also
# fitness score. So lower the score, better the route.
fitnes_list

array([8008., 7928., 6542., 6215., 6900., 6119., 7098., 7005., 6528.,
       6953., 6667., 7724., 6698., 7663., 7129., 5416., 7266., 6886.,
       6086., 7028., 6551., 7433., 7799., 6970., 6232., 7414., 7597.,
       5848., 7690., 7348., 7816., 6595., 6650., 4794., 7892., 6638.,
       7008., 7083., 7885., 7132., 6684., 6932., 6304., 7865., 6853.,
       5371., 7150., 6521., 6474., 7275., 7418., 6617., 5225., 6124.,
       7500., 6730., 6382., 7612., 7720., 6264., 7972., 5892., 6971.,
       6316., 7591., 7033., 6651., 6040., 6327., 6184., 6597., 6602.,
       5990., 6730., 6816., 5872., 6374., 6231., 7442., 5937., 5475.,
       6644., 6938., 7042., 5872., 7039., 5519., 6328., 6510., 6406.,
       5421., 5908., 5573., 7611., 7696., 7628., 6524., 7341., 7343.,
       6715., 7015., 6417., 6827., 5638., 7111., 7032., 6556., 6040.,
       7746., 7705., 8140., 6918., 6689., 6700., 7693., 6958., 6332.,
       7476., 7371., 6610., 6200., 6002., 8193., 7123., 6479., 6179.,
       6225., 5994.,

In [19]:
# Now that we have score for each of the 100 populated routes, we will
# pick the best routes from the lot.

def progenitor_selection(population_set,fitnes_list):
    fitnes_list=(fitnes_list.max()-fitnes_list)/fitnes_list.sum()
    total_fit = fitnes_list.sum()
    prob_list = fitnes_list/total_fit

    # print (f'total_fit = {total_fit}\n')
    # print (f'prob_list = {prob_list}\n')

    #Notice there is the chance that a progenitor. mates with oneself
    progenitor_list_a = np.random.choice(list(range(len(population_set))), len(population_set),p=prob_list, replace=True)
    progenitor_list_b = np.random.choice(list(range(len(population_set))), len(population_set),p=prob_list,replace=True)

    # print (f'progenitor_list_a [before] = {progenitor_list_a}\n')
    # print (f'progenitor_list_b [before] = {progenitor_list_b}\n')


    progenitor_list_a = population_set[progenitor_list_a]
    progenitor_list_b = population_set[progenitor_list_b]

    # print (f'progenitor_list_a [after] = {progenitor_list_a}\n')
    # print (f'progenitor_list_b [after] = {progenitor_list_b}\n')


    return np.array([progenitor_list_a,progenitor_list_b])


progenitor_list = progenitor_selection(population_set,fitnes_list)
progenitor_list[0][2]

array([ 1,  7,  9,  8,  2,  4, 10, 11, 12,  3,  5,  6,  0, 13])

In [20]:
# Crossover fn.
# Crossover is done as follows:
# Select first 6 cities from progenitor list1
# Select next set of cities from progenitor list2, but
# only if the city was not already picked from list1

def mate_progenitors(prog_a, prog_b):
    offspring = prog_a[0:5]

    for city in prog_b:

        if not city in offspring:
            offspring = np.concatenate((offspring,[city]))

    return offspring


# We receive progenitor_list which is a 2x100 array set.
# Among this, we select the the higher order array set
# i.e. progenitor_list[1][100]
# And then create a new population set of 100 city routes, again.

def mate_population(progenitor_list):
    new_population_set = []
    # print('Length of progenitor_list = ' + str(len(progenitor_list)))
    # print(f'progenitor_list = {progenitor_list}')
    # print(f'progenitor_list.shape[0] = {progenitor_list.shape[0]}')
    # print(f'progenitor_list.shape[1] = {progenitor_list.shape[1]}')

    for i in range(progenitor_list.shape[1]):
        prog_a, prog_b = progenitor_list[0][i], progenitor_list[1][i]
        offspring = mate_progenitors(prog_a, prog_b)
        new_population_set.append(offspring)

    return new_population_set

new_population_set = mate_population(progenitor_list)
print(new_population_set)
new_population_set[0]

[array([ 7,  8, 10,  1, 13,  0,  4,  3, 12,  5,  6, 11,  9,  2]), array([ 2,  0,  6, 12,  5,  4,  9,  8, 10, 11,  1, 13,  7,  3]), array([ 1,  7,  9,  8,  2,  6,  0,  3,  5, 10,  4, 12, 13, 11]), array([ 3,  0,  7, 12,  6, 11,  5,  4, 13,  1,  2,  9, 10,  8]), array([12, 13,  8,  9, 11,  7,  5,  4,  0,  6,  3,  2, 10,  1]), array([ 1, 10,  5, 11,  8,  6,  2,  7, 12, 13,  9,  0,  3,  4]), array([ 8,  3,  2,  7,  4,  9, 12, 10,  5,  1,  6,  0, 13, 11]), array([ 2, 13,  6, 11,  5,  8, 10,  4,  9,  1,  3, 12,  7,  0]), array([ 3,  8,  0,  9,  2, 12,  1,  7,  4, 10, 13,  5, 11,  6]), array([12,  9, 10,  4, 13,  0,  2, 11,  1,  3,  7,  8,  6,  5]), array([13,  5,  0,  2,  6,  1,  7,  9,  8,  4, 10, 11, 12,  3]), array([ 4, 13,  0,  5, 12,  7,  8,  6,  1, 10,  2, 11,  3,  9]), array([ 6,  8, 10,  0,  7,  3,  9, 11,  2,  1,  5, 13, 12,  4]), array([ 8,  9, 10, 11, 13,  5,  3,  7,  6,  1,  2, 12,  4,  0]), array([ 3, 11, 12,  4, 10, 13,  9,  1,  0,  6,  8,  5,  2,  7]), array([ 4,  3,  2,  6, 1

array([ 7,  8, 10,  1, 13,  0,  4,  3, 12,  5,  6, 11,  9,  2])

In [21]:
def mutate_offspring(offspring):
    for q in range(int(n_cities*mutation_rate)):
        a = np.random.randint(0,n_cities)
        b = np.random.randint(0,n_cities)

        # print(f'a = {a}, b = {b}')

        # Swap the two cities a & b
        # print(f'[Before] offspring[a] = {offspring[a]}, offspring[b] = {offspring[b]}')
        offspring[a], offspring[b] = offspring[b], offspring[a]
        # print(f'[After] offspring[a] = {offspring[a]}, offspring[b] = {offspring[b]}')

    return offspring


def mutate_population(new_population_set):
    mutated_pop = []
    for offspring in new_population_set:
        mutated_pop.append(mutate_offspring(offspring))
    return mutated_pop



# With new population set now available through cross over,
# we will now go through the mutation process.
mutated_pop = mutate_population(new_population_set)
print('-' * 60)
print(mutated_pop[0])
print('-' * 60)

------------------------------------------------------------
[ 7  8  2  1 13  0  4  3 12  5 10 11  9  6]
------------------------------------------------------------


In [22]:
# Finally, let us look at the best solution for the
# mutated population again.

# Initialize best_solution
best_solution = [-1,np.inf,np.array([])]

best_route = []

# Loop through 10000 iterations for the genetic algo. solution to converge
for i in range(10000):
    # Print every 100th loop
    if i%100==0: print(i, fitnes_list.min(), fitnes_list.mean(), datetime.now().strftime("%d/%m/%y %H:%M"))
    fitnes_list = get_all_fitnes(mutated_pop)

    #Saving the best solution if current value is better than previously saved one
    if fitnes_list.min() < best_solution[1]:
        best_solution[0] = i
        best_solution[1] = fitnes_list.min()
        best_solution[2] = np.array(mutated_pop)[fitnes_list.min() == fitnes_list]

    # Repeat crossover for currently iterated population data
    progenitor_list = progenitor_selection(population_set,fitnes_list)
    new_population_set = mate_population(progenitor_list)

    # Repeat mutation for currently iterated population data
    mutated_pop = mutate_population(new_population_set)

0 4611.0 6693.465 18/11/23 00:16
100 4157.0 6630.5125 18/11/23 00:16
200 4854.0 6684.13 18/11/23 00:16
300 4422.0 6658.205 18/11/23 00:16
400 4247.0 6718.8825 18/11/23 00:16
500 4373.0 6660.325 18/11/23 00:16
600 4493.0 6689.2475 18/11/23 00:16
700 4702.0 6609.2925 18/11/23 00:16
800 4917.0 6694.1225 18/11/23 00:16
900 4689.0 6627.5975 18/11/23 00:16
1000 4605.0 6703.0275 18/11/23 00:16
1100 4935.0 6664.43 18/11/23 00:16
1200 5117.0 6711.7275 18/11/23 00:16
1300 4831.0 6688.5925 18/11/23 00:16
1400 4765.0 6684.7425 18/11/23 00:16
1500 4510.0 6658.77 18/11/23 00:17
1600 4503.0 6713.6525 18/11/23 00:17
1700 4513.0 6627.6575 18/11/23 00:17
1800 4937.0 6725.805 18/11/23 00:17
1900 4614.0 6700.53 18/11/23 00:17
2000 4918.0 6708.305 18/11/23 00:17
2100 4619.0 6618.12 18/11/23 00:17
2200 4779.0 6708.035 18/11/23 00:17
2300 4316.0 6732.76 18/11/23 00:17
2400 4740.0 6621.9675 18/11/23 00:17
2500 4744.0 6684.9375 18/11/23 00:17
2600 4927.0 6719.495 18/11/23 00:17
2700 4974.0 6698.6525 18/11/23 0

In [23]:
best_solution

[9741,
 3503.0,
 array([[10,  8,  9,  0, 12,  6, 11,  5,  4,  3, 13,  2,  1,  7]])]